# Generated by Django 3.2 on 2022-12-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido del cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='cliente', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre Completo'),
        ),
    ]
